package lexico;

public enum TipoToken {
    /*
    PCDeclaracoes, PCAlgoritmo, PCInteiro, PCReal, PCAtribuir, PCA, PCLer,
    PCImprimir, PCSe, PCEntao, PCEquanto, PCInicio, PCFim,
    OpAriMult, OpAritDiv, OpAritSoma, OpAritSub,
    OpRelMenor, OpRelMenorIgual, OpRelMaiorIgual,
    OpRelMaior, OpRelIgual, OpRelDif,
    OpBoolE, OpBoolOu,
    Delim, AbrePar, FecharPar, Var, NumInt, NumReal, FimCadeia, Fim
    */
    EOF,
    ID,
    CTE_FLOAT,
    CTE_INT,
    CTE_CHAR,
    OP_ATR,
    OP_REL,
    OP_AD,
    OP_SUB,
    OP_MULT,
    OP_DIV,
    OP_RES,
    OP_GREATER,
    OP_LESS,
    OP_GREATEREQ,
    OP_LESSEQ,
    OP_NOT,
    OP_NOTUN,
    COMMENT,
    PR_AND,
    PR_OR,
    PR_FUNCTION,
    PR_REFOUND,
    PR_IF,
    PR_ELSE,
    PR_WHILE,
    PR_FORREPEAT,
    PR_INTEGER,
    PR_FLOAT,
    PR_CHARACTERARRAY,
    PR_CHARACTER,
    PR_BOOL,
    PR_INPUT,
    PR_PRINT,
    PR_PRINTNL,
    PR_TRUE,
    PR_FALSE,
    PR_NULL,
    PR_BEGIN,
    PR_END,
    AB_PAR,
    FEC_PAR,
    AB_COL,
    FEC_COL,
    PR_VOID,
    PR_MAIN,
    TERMINAL,
    SEP;

}
